### ISSUE TITLE
Nuget package - Db type neutral

### ISSUE THREAD

**Issue by satyajit-behera** [rjperes/EFAuditable#1]
Hi,

It may be good to have Microsoft.EntityFrameworkCore.Relational instead of Microsoft.EntityFrameworkCore.SqlServer and keep it completely Db neutral for a relational database.

Thanks

**Comment by rjperes** [comment]
Good point, thanks!

**Comment by rjperes** [comment]
Fixed on 1f22a1f542b20067d560d5af737fc50332e4f7be.
